image: 'rust:latest'

cache:
  paths:
    - cargo/

stages:
  - build
  - test
  - integration-test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

.only-mr-and-master:
  only:
    - master
    - merge_requests

build:
  stage: build
  extends: .only-mr-and-master
  script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
  artifacts:
    expire_in: 1 hour
    paths:
      - cargo/
      - target/

test:
  stage: test
  extends: .only-mr-and-master
  script:
    - cargo test --verbose

.lua-setup:
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y python python-pip
    - python --version
    - chmod u+x ./bin/install-lua.sh
    - ./bin/install-lua.sh
    - export PATH=$PATH:$PWD/lua_install/bin

test-lua-projects:
  stage: integration-test
  extends:
    - .only-mr-and-master
    - .lua-setup
  script:
    - lua ./bin/test-commands.lua
